app/yuyakake/urls.py
from django.urls import path, include

from .views.cakesizeview import ListarCakeSizeView, CrearCakeSizeView
from .views.configuracionview import ListarConfiguracionView, CrearConfiguracionView
from .views.merengueview import ListarMerengueView, CrearMerengueView
from .views.pisosview import ListarPisosView, CrearPisosView
from .views.views import *
from .views.cakebaseviews import ListarBaseView, CrearBaseView

urlpatterns = [
    path('new-order/', CreateOrder.as_view(), name='new_order'),

    # Capas
    path('base_list/', ListarBaseView.as_view(), name='base_list'),
    path('base_new/', CrearBaseView.as_view(), name='base_new'),

    # Size
    path('size_list/', ListarCakeSizeView.as_view(), name='size_list'),
    path('size_new/', CrearCakeSizeView.as_view(), name='size_new'),

    # Merengue
    path('merengue_list/', ListarMerengueView.as_view(), name='merengue_list'),
    path('merengue_new/', CrearMerengueView.as_view(), name='merengue_new'),

    # Pisos
    path('pisos_list/', ListarPisosView.as_view(), name='pisos_list'),
    path('pisos_new/', CrearPisosView.as_view(), name='pisos_new'),

    # Cake
    path('cake_list/', ListarConfiguracionView.as_view(), name='cake_list'),
    path('cake_new/', CrearConfiguracionView.as_view(), name='cake_new'),

    # Cargar partes
    path('load_merengue/', cargar_merengue, name='load_merengue'),
    path('load_size/', cargar_size, name='load_size'),
    path('cargar_base/', cargar_base, name='cargar_base'),
    path('cargar_pisos/', cargar_pisos, name='cargar_pisos'),

    # Get Partes
    path('get_merengue/', get_merengue, name='get_merengue'),
    path('get_base/', get_base, name='get_base'),
    path('get_pisos/', get_pisos, name='get_pisos'),
    path('get_size/', get_size, name='get_size'),

    # get muestra pastel
    path('get_cake_sample/', get_cake_sample_ajax, name='get_cake_sample'),
    path('get_cakesamples/', get_cakesamples, name='get_cakesamples'),

]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from settings import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),


    # "Landing Page" #
    path('', include('app.landingpage.urls')),
    # "End" #

    # "Landing Customers" #
    path('', include('app.customUser.urls')),
    # "End" #

    # "Home Page" #
    path('home/', include('app.yuyakake.urls')),
    # "End" #

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/yuyakake/models.py
from django.contrib.auth.models import User
from django.db import models


class CakeBase(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='base/')
    disponible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def serialize(self):
        return {
            'id': self.id,
            'name': self.name,
            'image': self.image.url if self.image else ''
        }

class CakeLayer(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='layers/')
    disponible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def serialize(self):
        return {
            'id': self.id,
            'name': self.name,
            'image': self.image.url if self.image else ''
        }

class CakeMeringue(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='meringues/')
    disponible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def serialize(self):
        return {
            'id': self.id,
            'name': self.name,
            'image': self.image.url if self.image else ''
        }

class CakeSize(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='sizes/')
    disponible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def serialize(self):
        return {
            'id': self.id,
            'name': self.name,
            'image': self.image.url if self.image else ''
        }

class Cake(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='cakes/')
    base = models.ForeignKey(CakeBase, on_delete=models.CASCADE)
    layers = models.ForeignKey(CakeLayer, on_delete=models.CASCADE)
    filling = models.TextField()
    meringue = models.ForeignKey(CakeMeringue, on_delete=models.CASCADE)
    size = models.ForeignKey(CakeSize, on_delete=models.CASCADE)
    rating = models.DecimalField(max_digits=3, decimal_places=2, default=0)

    def __str__(self):
        return self.name


from django.db.models.signals import post_save
from django.dispatch import receiver

class CakeSample(models.Model):
    cake = models.ForeignKey(Cake, on_delete=models.PROTECT, related_name='samples')
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='samples/')
    base = models.ForeignKey(CakeBase, on_delete=models.PROTECT)
    layers = models.ForeignKey(CakeLayer, on_delete=models.PROTECT)
    filling = models.TextField()
    meringue = models.ForeignKey(CakeMeringue, on_delete=models.PROTECT)
    size = models.ForeignKey(CakeSize, on_delete=models.PROTECT)
    #datecreated

    def __str__(self):
        return f"{self.name} ({self.cake.name})"

    def serialize(self):
        return {
            'id': self.id,
            'name': self.name,
            'image': self.image.url if self.image else '',
            'base': self.base.name if self.image else '',
            'layers': self.layers.name if self.image else '',
            'filling': self.filling if self.image else '',
            'meringue': self.meringue.name if self.image else '',
            'size': self.size.name if self.image else '',
        }
    
class CakeReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cake = models.ForeignKey(Cake, on_delete=models.CASCADE)
    rating = models.DecimalField(max_digits=3, decimal_places=2)
    review = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.cake.name} review by {self.user.username}"
class Order(models.Model):
    STATE_CHOICES = [
        ('P', 'Pendiente'),
        ('E', 'En preparación'),
        ('L', 'Listo para recoger'),
        ('C', 'Completado'),
        ('X', 'Cancelado'),
    ]
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    delivery_address = models.CharField(max_length=200)
    delivery_date = models.DateField()
    delivery_time = models.TimeField()
    notes = models.TextField(blank=True)
    state = models.CharField(max_length=1, choices=STATE_CHOICES, default='P')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.customer.username} ({self.delivery_date})"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    cake = models.ForeignKey(Cake, on_delete=models.CASCADE)
    sample = models.ForeignKey(CakeSample, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.quantity} x {self.cake.name} ({self.sample.name})"

app/yuyakake/forms.py
from django.forms import *

from app.yuyakake.models import CakeBase, CakeSize, CakeMeringue, CakeLayer, Cake


class CreateBaseForm(ModelForm):
    class Meta:
        model = CakeBase
        fields = '__all__'

class CreateCakeSizeForm(ModelForm):
    class Meta:
        model = CakeSize
        fields = '__all__'


class CreateMerengueForm(ModelForm):
    class Meta:
        model = CakeMeringue
        fields = '__all__'


class CreatePisosForm(ModelForm):
    class Meta:
        model = CakeLayer
        fields = '__all__'


class CreateCakeForm(ModelForm):
    class Meta:
        model = Cake
        fields = '__all__'

app/yuyakake/views/cakebaseviews.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.views.generic import TemplateView,ListView, CreateView
from django.urls import reverse_lazy

from app.yuyakake.forms import CreateBaseForm
from app.yuyakake.models import CakeBase


class ListarBaseView(UserPassesTestMixin, ListView):
    template_name = 'cake/base/listar.html'
    model = CakeBase

    def test_func(self):
        return self.request.user.is_superuser


class CrearBaseView(UserPassesTestMixin, CreateView):
    model = CakeBase
    template_name = 'cake/base/crear.html'
    form_class = CreateBaseForm
    success_url = reverse_lazy('base_list')

    def test_func(self):
        return self.request.user.is_superuser

app/yuyakake/views/cakesizeview.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.views.generic import TemplateView, ListView, CreateView
from django.urls import reverse_lazy

from app.yuyakake.forms import CreateBaseForm, CreateCakeSizeForm
from app.yuyakake.models import CakeSize


class ListarCakeSizeView(UserPassesTestMixin, ListView):
    template_name = 'cake/size/listar.html'
    model = CakeSize

    def test_func(self):
        return self.request.user.is_superuser


class CrearCakeSizeView(UserPassesTestMixin, CreateView):
    model = CakeSize
    template_name = 'cake/size/crear.html'
    form_class = CreateCakeSizeForm
    success_url = reverse_lazy('size_list')

    def test_func(self):
        return self.request.user.is_superuser

app/yuyakake/views/configuracionview.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import TemplateView, ListView, CreateView
from django.urls import reverse_lazy
from app.yuyakake.forms import CreateCakeForm
from app.yuyakake.models import Cake


class ListarConfiguracionView(UserPassesTestMixin, ListView):
    template_name = 'cake/configuracion/listar.html'
    model = Cake

    def test_func(self):
        return self.request.user.is_superuser


class CrearConfiguracionView(UserPassesTestMixin, CreateView):
    model = Cake
    template_name = 'cake/configuracion/crear.html'
    form_class = CreateCakeForm
    success_url = reverse_lazy('cake_list')

    def test_func(self):
        return self.request.user.is_superuser

app/yuyakake/views/merengueview.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import TemplateView, ListView, CreateView
from django.urls import reverse_lazy
from app.yuyakake.forms import CreateMerengueForm
from app.yuyakake.models import CakeMeringue


class ListarMerengueView(UserPassesTestMixin, ListView):
    template_name = 'cake/merengue/listar.html'
    model = CakeMeringue

    def test_func(self):
        return self.request.user.is_superuser


class CrearMerengueView(UserPassesTestMixin,CreateView):
    model = CakeMeringue
    template_name = 'cake/merengue/crear.html'
    form_class = CreateMerengueForm
    success_url = reverse_lazy('merengue_list')

    def test_func(self):
        return self.request.user.is_superuser

app/yuyakake/views/pisosview.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import TemplateView, ListView, CreateView
from django.urls import reverse_lazy
from app.yuyakake.forms import CreateMerengueForm, CreatePisosForm
from app.yuyakake.models import CakeLayer


class ListarPisosView(UserPassesTestMixin, ListView):
    template_name = 'cake/pisos/listar.html'
    model = CakeLayer

    def test_func(self):
        return self.request.user.is_superuser


class CrearPisosView(UserPassesTestMixin,CreateView):
    model = CakeLayer
    template_name = 'cake/pisos/crear.html'
    form_class = CreatePisosForm
    success_url = reverse_lazy('pisos_list')

    def test_func(self):
        return self.request.user.is_superuser

app/yuyakake/views/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, CreateView
from app.yuyakake.models import CakeMeringue, CakeBase, CakeLayer, CakeSize, CakeSample
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.shortcuts import get_object_or_404
from app.yuyakake.models import CakeMeringue
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from PIL import Image, ImageOps

class CreateOrder(LoginRequiredMixin, CreateView):
    template_name = 'orders/new_order.html'

@login_required
def cargar_merengue(request):
    objs = CakeMeringue.objects.filter(disponible=True)
    data = [{'id': obj.id, 'name': obj.name} for obj in objs]
    return JsonResponse(data, safe=False)


@login_required
def cargar_base(request):
    objs = CakeBase.objects.filter(disponible=True)
    data = [{'id': obj.id, 'name': obj.name} for obj in objs]
    return JsonResponse(data, safe=False)


@login_required
def cargar_pisos(request):
    objs = CakeLayer.objects.filter(disponible=True)
    data = [{'id': obj.id, 'name': obj.name} for obj in objs]
    return JsonResponse(data, safe=False)

@login_required
def cargar_size(request):
    objs = CakeSize.objects.filter(disponible=True)
    data = [{'id': obj.id, 'name': obj.name} for obj in objs]
    return JsonResponse(data, safe=False)

from django.contrib.auth.decorators import login_required


@login_required
@require_http_methods(['GET'])
def get_merengue(request):
    merengue_id = request.GET.get('id')
    print(merengue_id)
    merengue = get_object_or_404(CakeMeringue, id=merengue_id)
    return JsonResponse({'merengue': merengue.serialize()})


@login_required
@require_http_methods(['GET'])
def get_base(request):
    base_id = request.GET.get('id')
    base = get_object_or_404(CakeBase, id=base_id)
    return JsonResponse({'base': base.serialize()})


@login_required
@require_http_methods(['GET'])
def get_pisos(request):
    pisos_id = request.GET.get('id')
    pisos = get_object_or_404(CakeLayer, id=pisos_id)
    return JsonResponse({'pisos': pisos.serialize()})


@login_required
@require_http_methods(['GET'])
def get_size(request):
    size_id = request.GET.get('id')
    size = get_object_or_404(CakeSize, id=size_id)
    return JsonResponse({'size': size.serialize()})



@require_http_methods(['GET'])
def get_cakesamples(request):
    cakesamples = CakeSample.objects.all().order_by('cake__rating')
    data = []
    if cakesamples:
        for cakesample in cakesamples:
            # image_temp = Image.open(cakesample.image.url)
            # image_temp = ImageOps.fit(image_temp, (800, 600), Image.ANTIALIAS)
            # image_temp.save(cakesample.image.url)
            data.append({
                'id': cakesample.id,
                'name': cakesample.name,
                'description': cakesample.description,
                'image_url': cakesample.image.url
            })
        return JsonResponse(data, safe=False)
    else:
        return JsonResponse(
            {'error': 'No se encontró ninguna muestra de pastel que coincida con los valores dados.'})


def get_cake_sample(base, merengue, size, layers):
    """
    Función para buscar objetos CakeSample que coincidan con los objetos CakeBase, CakeMeringue, CakeSize y CakeLayer dados.
    Si se encuentran objetos CakeSample que coincidan, se devuelve una lista con todos los objetos encontrados. Si no se encuentra ningún objeto CakeSample que coincida, se devuelve None.
    """
    cake_samples = CakeSample.objects.filter(base=base, meringue=merengue, size=size, layers=layers)
    if cake_samples.exists():
        return list(cake_samples)
    else:
        return None



@login_required
@csrf_exempt
def get_cake_sample_ajax(request):
    """
    Vista para obtener un objeto CakeSample buscándolo por los atributos base, merengue, size y layers mediante una llamada Ajax con el método POST.
    Los valores de los atributos se pasan en el cuerpo de la solicitud como datos POST.
    """
    if request.method == 'POST':
        base_id = request.POST.get('base_id')
        merengue_id = request.POST.get('merengue_id')
        size_id = request.POST.get('size_id')
        layers_id = request.POST.get('layers_id')

        # Se obtienen los objetos CakeBase, CakeMeringue, CakeSize y CakeLayer correspondientes a los IDs dados
        base = CakeBase.objects.get(id=base_id)
        merengue = CakeMeringue.objects.get(id=merengue_id)
        size = CakeSize.objects.get(id=size_id)
        layers = CakeLayer.objects.get(id=layers_id)

        # Se busca el objeto CakeSample que coincida con los valores dados
        cake_samples = get_cake_sample(base, merengue, size, layers)

        if cake_samples is not None:
            # Se convierte cada objeto CakeSample a un diccionario de Python serializable
            response_data = []
            for cake_sample in cake_samples:
                cake_sample_dict = {
                    'name': cake_sample.name,
                    'description': cake_sample.description,
                    'image_url': cake_sample.image.url,
                    'filling': cake_sample.filling
                }
                response_data.append(cake_sample_dict)

            return JsonResponse(response_data, safe=False)
        else:
            return JsonResponse(
                {'error': 'No se encontró ninguna muestra de pastel que coincida con los valores dados.'})

app/yuyakake/templates/orders/new_order.html
{% load static %}
<!-- order a cake section starts -->
<style>
    #galeria-imagenes {
        position: relative;
    }

    #galeria-imagenes img.seleccionado {
        border: 2px solid red;
        width: 70%;
        height: auto;
        position: relative;
        z-index: 1;
        margin: 0 auto;
    }

    #galeria-imagenes .zoom {
        width: 80px;
        height: 80px;
        border-radius: 50%;
        background-color: rgba(255, 255, 255, 0.5);
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) scale(0.8);
        display: none;
        z-index: 2;
        pointer-events: none;
    }

    #galeria-imagenes img.seleccionado:hover + .zoom {
        display: block;
    }

    #galeria-imagenes .zoom:before {
        content: '';
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) scale(0.8);
        width: 100%;
        height: 100%;
        border-radius: 50%;


        border-color: green;

        transition: transform 0.3s ease-in-out;
    }

    #galeria-imagenes img.seleccionado:hover + .zoom:before {
        transform: translate(-50%, -50%) scale(1.2);
    }

    #galeria-zoom {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        z-index: 2;
        pointer-events: none;
    }

    #galeria-zoom .zoom {
        width: 80px;
        height: 80px;
        border-radius: 50%;
        background-color: #CC3434;

    }

    #galeria-imagenes img.seleccionado:hover + #galeria-zoom .zoom {
        display: block;
    }

    #galeria-zoom .zoom:before {
        content: '';
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) scale(0.8);
        width: 100%;
        height: 100%;
        border-radius: 50%;
        border: 2px solid red;
        transition: transform 0.3s ease-in-out;
    }

    #galeria-imagenes img.seleccionado:hover + #galeria-zoom .zoom:before {
        transform: translate(-50%, -50%) scale(1.2);
    }

    #galeria-imagenes {
        position: relative;
    }

    #galeria-imagenes img.seleccionado {
        border: 2px solid red;
        width: 70%;
        height: auto;
        position: relative;
        z-index: 1;
        margin: 0 auto;
    }

    #galeria-zoom {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        z-index: 2;
        pointer-events: none;
    }

    #galeria-zoom .zoom {
        width: 80px;
        height: 80px;
        border-radius: 50%;
        background-color: rgba(255, 255, 255, 0.5);
        display: none;
    }

    #galeria-imagenes img.seleccionado:hover + #galeria-zoom .zoom {
        display: block;
    }

    #galeria-zoom .zoom:before {
        content: '';
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) scale(0.8);
        width: 100%;
        height: 100%;
        border-radius: 50%;
        border: 2px solid red;
        transition: transform 0.3s ease-in-out;
    }

    #galeria-imagenes img.seleccionado:hover + #galeria-zoom .zoom:before {
        transform: translate(-50%, -50%) scale(1.2);
    }

    {#<!--#}
    {#-->#}

    #galeria-imagenes {
        display: flex;
        flex-wrap: wrap;
    }

    #galeria-imagenes img {
        width: 100px;
        height: 100px;
        object-fit: cover;
        margin: 10px;
        cursor: pointer;
    }

    select.custom-select:valid {
        box-shadow: none;
    }

    .image-container {
        background: radial-gradient(ellipse 60% 70% at center, rgba(255, 255, 255, 0.5) 50%, transparent 75%);
        overflow: hidden;
    }

    .image-container img {
        width: 70%;
        height: auto;
        margin: 0 auto;
        display: block;
    }

    .text {
        text-align: center;
    }

    .rounded-circle {
        border-radius: 50%;
    }


</style>

<section class="ftco-section img" id="order" style="background-image: url({% static 'images/order_bg.jpg' %});"
         data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="col ftco-animate makereservation p-4 px-md-5 pb-md-5">
                    <!-- Contenido de la columna aquí -->
                    <div class="heading-section ftco-animate mb-5 text-center">
                        <span class="subheading">Order</span>
                        <h2 class="mb-4">Your Cake</h2>
                    </div>
                    <form class="needs-validation" novalidate method="post" id="create-form">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="categoria">Base:</label>
                                    <select class="select form-select" name="base" id="id_base"></select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Dirección:</label>
                                    <input class="form-control" id="id_addres" name="addres"
                                           placeholder="dirección particular">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="categoria">Tamaño:</label>
                                    <select class="select form-select" name="size" id="id_size"></select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="telefono" class="form-label">Teléfono:</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <select id="telefono-prefijo" name="telefono-prefijo"
                                                    class="form-select custom-select" novalidate>
                                                <option value="+53">+53</option>
                                                <option value="+51">+51</option>
                                            </select>
                                        </div>
                                        <input type="number" id="telefono-resto" name="telefono-resto"
                                               class="form-control"
                                               pattern="^[1-9]\d{7}$" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="categoria">Merengue:</label>
                                    <select class="select form-select" name="merengue" id="id_merengue"></select>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="categoria">Pisos:</label>
                                    <select class="select form-select" name="pisos" id="id_pisos"></select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="">Fecha de entrega:</label>
                                    <div class="col-auto" id="calendario"></div>
                                </div>
                            </div>


                            <div class="col-md-12 mt-3">
                                <div class="form-group text-center">
                                    <input type="submit" value="Order Your Cake" class="btn btn-primary py-3 px-5">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- Vendor Image Files -->
            <div class="col-6 h-50  ">
                <div class="row mt-5">
                    <div class="col-3 text-center ">
                        <div class="h-75 my-5">
                            <img class="rounded-circle"
                                 src="" id="base-imagen"
                                 style="width: 100%;height: 100%; background: #bfbfbf">
                            <div class="mt-2 ">
                                <strong>
                                    <span class="text p-3"
                                          style="background: radial-gradient(ellipse 60% 70% at center, rgba(255, 255, 255, 0.5) 50%,
                                          transparent 75%)">Base</span>
                                </strong>
                            </div>
                        </div>
                    </div>

                    <div class="col-3 text-center ">
                        <div class="h-75 my-5">
                            <img class="rounded-circle"
                                 src="" id="size-imagen"
                                 style="width: 100%;height: 100%; background: #bfbfbf">
                            <div class="mt-2 ">
                                <strong>
                                    <span class="text p-3"
                                          style="background: radial-gradient(ellipse 60% 70% at center, rgba(255, 255, 255, 0.5) 50%,
                                          transparent 75%)">Tamaño</span>
                                </strong>
                            </div>
                        </div>
                    </div>
                    <div class="col-3 text-center ">
                        <div class="h-75 my-5">
                            <img class="rounded-circle"
                                 src="" id="merengue-imagen"
                                 style="width: 100%;height: 100%; background: #bfbfbf">
                            <div class="mt-2 ">
                                <strong>
                                    <span class="text p-3"
                                          style="background: radial-gradient(ellipse 60% 70% at center, rgba(255, 255, 255, 0.5) 50%,
                                          transparent 75%)">Merengue</span>
                                </strong>
                            </div>
                        </div>
                    </div>
                    <div class="col-3 text-center ">
                        <div class="h-75 my-5">
                            <img class="rounded-circle"
                                 src="" id="pisos-imagen"
                                 style="width: 100%;height: 100%; background: #bfbfbf">
                            <div class="mt-2 ">
                                <strong>
                                    <span class="text p-3"
                                          style="background: radial-gradient(ellipse 60% 70% at center, rgba(255, 255, 255, 0.5) 50%,
                                          transparent 75%)">Pisos</span>
                                </strong>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="row mt-3">
                    <div class="h-100 mt-5" id="galeria-imagenes">
                    </div>
                    <div id="galeria-zoom">
                        <div class="zoom">asdasd</div>
                    </div>

                </div>
            </div>

        </div>
    </div>


    </div>

</section>
<!-- order a cake section ends -->